package api

import (
	"net/http"

	// docs is generated by Swag CLI, you have to import it.
	contentapi "github.com/crikke/cms/pkg/contentmanagement/api/v1/content"
	contentdefapi "github.com/crikke/cms/pkg/contentmanagement/api/v1/contentdefinition"
	cfgapi "github.com/crikke/cms/pkg/contentmanagement/api/v1/siteconfiguration"
	"github.com/crikke/cms/pkg/workspace"

	"github.com/crikke/cms/pkg/content"
	"github.com/crikke/cms/pkg/contentdefinition"
	"github.com/crikke/cms/pkg/contentmanagement/app"
	"github.com/crikke/cms/pkg/contentmanagement/app/command"
	"github.com/crikke/cms/pkg/contentmanagement/app/query"
	"github.com/crikke/cms/pkg/siteconfiguration"
	"github.com/go-chi/chi/v5"
	"go.mongodb.org/mongo-driver/mongo"
)

func NewContentManagementAPI(c *mongo.Client, eventhandler siteconfiguration.ConfigurationEventHandler, cfg *siteconfiguration.SiteConfiguration) http.Handler {

	// docs.SwaggerInfo.Title = "Content management API"
	// docs.SwaggerInfo.Version = "0.1.0"
	// docs.SwaggerInfo.Description = "This api is responsible for managing content."
	// docs.SwaggerInfo.Host = "localhost:8080"
	// docs.SwaggerInfo.BasePath = "/contentmanagement/"

	app := initializeHandlers(c, eventhandler, cfg)

	r := chi.NewRouter()

	contentendpoint := contentapi.NewContentEndpoint(app)
	contentendpoint.RegisterEndpoints(r)

	contentdefendpoint := contentdefapi.NewContentDefinitionEndpoint(app)
	contentdefendpoint.RegisterEndpoints(r)

	r.Mount("/siteconfiguration", cfgapi.NewSiteConfigurationRouter(cfg))

	return r
}

func initializeHandlers(c *mongo.Client, eventhandler siteconfiguration.ConfigurationEventHandler, cfg *siteconfiguration.SiteConfiguration) app.App {

	contentRepo := content.NewContentRepository(c)
	contentDefinitionRepo := contentdefinition.NewContentDefinitionRepository(c)
	configRepo := siteconfiguration.NewConfigurationRepository(c)
	workspaceRepo := workspace.NewWorkspaceRepository(c)

	app := app.App{
		Queries: app.Queries{
			GetContent: query.GetContentHandler{
				Repo: contentRepo,
			},
			ListContent: query.ListContentHandler{
				Repo: contentRepo,
			},
			GetContentDefinition: query.GetContentDefinitionHandler{
				Repo: contentDefinitionRepo,
			},
			GetPropertyDefinition: query.GetPropertyDefinitionHandler{
				Repo: contentDefinitionRepo,
			},
			ListContentDefinitions: query.ListContentDefinitionHandler{
				Repo: contentDefinitionRepo,
			},
			WorkspaceQueries: app.WorkspaceQueries{
				GetWorkspace: query.GetWorkspaceHandler{
					Repo: workspaceRepo,
				},
			},
		},
		Commands: app.Commands{
			CreateContent: command.CreateContentHandler{
				ContentDefinitionRepository: contentDefinitionRepo,
				ContentRepository:           contentRepo,
				Factory:                     content.Factory{Cfg: cfg},
			},
			UpdateContentFields: command.UpdateContentFieldsHandler{
				ContentRepository:           contentRepo,
				ContentDefinitionRepository: contentDefinitionRepo,
				Factory:                     content.Factory{Cfg: cfg},
			},
			ArchiveContent: command.ArchiveContentHandler{
				ContentRepository: contentRepo,
			},
			PublishContent: command.PublishContentHandler{
				ContentDefinitionRepository: contentDefinitionRepo,
				ContentRepository:           contentRepo,
				SiteConfiguration:           cfg,
			},
			CreateContentDefinition: command.CreateContentDefinitionHandler{
				Repo: contentDefinitionRepo,
			},
			UpdateContentDefinition: command.UpdateContentDefinitionHandler{
				Repo: contentDefinitionRepo,
			},
			DeleteContentDefinition: command.DeleteContentDefinitionHandler{},
			CreatePropertyDefinition: command.CreatePropertyDefinitionHandler{
				Repo:    contentDefinitionRepo,
				Factory: contentdefinition.PropertyDefinitionFactory{},
			},
			UpdatePropertyDefinition: command.UpdatePropertyDefinitionHandler{
				Repo: contentDefinitionRepo,
			},
			DeletePropertyDefinition: command.DeletePropertyDefinitionHandler{},
			UpdateSiteConfiguration: command.UpdateSiteConfigurationHandler{
				Cfg:          cfg,
				Repo:         configRepo,
				Eventhandler: eventhandler,
			},
			WorkspaceCommands: app.WorkspaceCommands{},
		},
	}

	return app
}
