name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: "Vet"
      run: make vet

    - name: "Unit tests"
      run: make test
    
    - name: "Integration test"
      run: make integration
      
